### ISSUE TITLE
Deps.clj for advanced examples?

### ISSUE THREAD

**Issue by aadrian** [kloimhardt/bb-web#1]
Hi,

Would https://github.com/borkdude/deps.clj work for https://github.com/kloimhardt/bb-web#add-javascript-libraries-for-use-with-babashka  so that one would not need to install Clojure for that case either?

Thank you.

**Comment by kloimhardt** [comment]
Truth is: You need to install and use Shadow-cljs (and thus Clojure on the JVM) for this advanced step.

I do not understand your reasoning how deps.clj can make the installation of Clojure unnecessary. In my understanding this is not the purpose of using deps.clj in any project. Maybe you mean that a certain bash shell script called "clojure" does not need to be installed when using deps.clj. This is indeed the case.

Most probably my Readme was misleading. I updated it in the hope to solve this issue.

**Comment by aadrian** [comment]
> You need to install and use Shadow-cljs

That's not an issue since it's portable and the same on every system `npm install -g shadow-cljs`
*(It also has the same arguments on all platforms)*

> I do not understand your reasoning how deps.clj can make the installation of Clojure unnecessary. 
> Maybe you mean that a certain bash shell script called "clojure" does not need to be installed when using deps.clj. 

Yes. The official Clojure installation is to this day stunningly bad and non-portable. It works "nicely" only on OSX.

On the other hand,  **[deps](https://github.com/borkdude/deps.clj)** works the same on every platform, it's only single exe that just needs to be on the path (same as with `bb`)

**Comment by kloimhardt** [comment]
First my apology:
I should have seen your point early on, which is that you want to enhance bb-web, yourself working on the native MS-Windows command line (and not WSL). In my defence I can say that I (up to now) thought that people interested in bb-web would never want to use JVM-Clojure on native Windows. It is especially unsuitable for beginners or even for, say, seasoned F# people who just want to try out Clojure.  I made bb-web exactly for this reason.

Now that I understand and find your suggestion valuable, here is why I would need your help to do this:
I develop on WSL. I would need to install JAVA, Shadow, NPM, Cider etc. on my native Windows to test how and if deps.clj and all really works there. I shy away from this. I had such a setup on a machine at my former workplace, to much frustration, but that admittedly was a while ago. FYI: the Babashka windows binary is produce via AppVayor, never on my local machine.

Can you give me a detailed description which files I need to add where in order that things would work for you?

**Comment by aadrian** [comment]
> Can you give me a detailed description which files I need to add where in order that things would work for you?

Thank you very much, but everything works for me :)  - you don't need to change anything.

Since your project description mentioned the use of BB (as an alternative to the cumbersome Clojure installation), and required Clojure installation only for the advanced example, I thought it might be good idea to cover those parts too, since the same author also made deps.clj (that has for all platforms a solution, not just windows).

For new users (especially windows) getting Clojure to work, especially since Clojure Tools were introducuced, it's a PITA, hence a combination of `bb.exe` and `deps.exe` on the path solves all the pain problems.

**Comment by kloimhardt** [comment]
TIL: it is indeed a natural thought to expect deps.clj being used in bb-web. Paradoxically, because I want to be the last one forced to use deps.clj in Windows, I created bb-web.
